openapi: 3.0.3
info:
  title: 파라미터 정의
  version: '-'

paths:

components:
  parameters:
    HeaderDeviceId:
      in: header
      name: Device-Id
      schema:
        type: string
      required: true
      example: 28f2654e-a99c-4805-902c-af1599360cde


